# Generated by Django 5.1 on 2025-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_adresse_patient_assurance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='nom',
            new_name='nom_complet',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='assurance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='contact_urgence',
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_relation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='nom_assurance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_police',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='resume_medical',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin'), ('Autre', 'Autre')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('En attente', 'En attente')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
