# Generated by Django 5.1 on 2025-06-20 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_rename_nom_patient_nom_complet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.CharField(max_length=255)),
                ('medecin', models.CharField(choices=[('Rakotomalala', 'Rakotomalala'), ('Mandria', 'Mandria'), ('Robin', 'Robin')], default='Rakotomalala', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patient.patient')),
            ],
        ),
    ]
